gui fixes
- fixes #164. Expanded the error message to name the layer and spatial field without associated spatial shapes for mapping. Should no longer cause the screen to gray, just a red message saying:

    Error: Sorry, the Map view is unavailable for the selected layer (fis_b_bmsy) because the field fao_id does not have associated spatial shapes available for mapping. Please choose a different view (Histogram or Table) or a different layer.

- fixes #95. Handled this odd single zero value condition by using an arbitrary range.

    rng = c(-1, 1) * 0.001

- fixes #165. Recently removed the scenario.R file since standardized expected names of files and folders within. Updated code to not require this file but still set vars for running rest of Calculate.