bug fix: subdir = file.path(dir_dest, 'eez2013')
Was getting error message:
get_scenarios('ohi-science/ohi-global', '~/ohi-global')
Error: file.exists(sprintf("%s/conf", dir_scenario)) is not TRUE

presumably because trying to set shortcuts to all folders, including the temp folder